fix: check canary prefix and remove forced unpublish

diff --git a/.github/actions/unpublish-canary/action.yml b/.github/actions/unpublish-canary/action.yml
--- a/.github/actions/unpublish-canary/action.yml
+++ b/.github/actions/unpublish-canary/action.yml
@@ -24,33 +24,49 @@ runs:
         node-version: 18
         registry-url: "https://registry.npmjs.org/"
 
+    - name: Validate canary_prefix input
+      id: validate_prefix
+      shell: bash
+      run: |
+        if [[ -z "${{ inputs.canary_prefix }}" ]]; then
+          echo "Error: canary_prefix is required but empty."
+          exit 1
+        fi
+
+        if [[ ! "${{ inputs.canary_prefix }}" == *"-canary"* ]]; then
+          echo "⛔️Error: version prefix ${{ inputs.canary_prefix }} must contain '-canary'."
+          exit 1
+        fi
+        echo "version prefix is valid: ${{ inputs.canary_prefix }}"
+
     - name: Remove old Canary versions
       id: unpublish_step
       shell: bash
       run: |
-        echo "Unpublishing versions for prefix: ${{ inputs.canary_prefix }}..."
-        VERSIONS=$(npm dist-tag ls execution-engine | grep "${{ inputs.canary_prefix }}" | awk '{print $2}')
-        RESULT=()  # Initialize an empty array
-
+        echo "⏳ Checking versions with prefix: ${{ inputs.canary_prefix }} ..."
+        VERSIONS=$(npm dist-tag ls execution-engine | grep "${{ inputs.canary_prefix }}" | awk '{print $2}' || true)
+        
+        # Check if VERSIONS is empty
         if [ -z "$VERSIONS" ]; then
-          echo "No versions found for prefix ${{ inputs.canary_prefix }}. Nothing to unpublish."
+          echo "✅ No versions found for prefix ${{ inputs.canary_prefix }}. Nothing to unpublish."
         else
+          RESULT=()  # Initialize an empty array
           for v in $VERSIONS; do
-            echo "Unpublishing version: $v"            
-            if npm unpublish --force execution-engine@$v; then
+            echo "⏳ Unpublishing version: $v"
+            if npm unpublish execution-engine@$v; then
+              echo "✅ Unpublished version: $v"
               RESULT+=("$v")  # Append each unpublished version to the array
             else
-              echo "Failed to unpublish version: $v"
+              echo "🚫 Failed to unpublish version: $v. Skipping."
             fi
           done
+        
+          # Convert array to a comma-separated string
+          RESULT_STRING=$(IFS=,; echo "${RESULT[*]}")
+        
+          # Set outputs
+          echo "result=$RESULT_STRING" >> $GITHUB_ENV
+          echo "result=$RESULT_STRING" >> $GITHUB_OUTPUT
         fi
-
-        # Convert array to a comma-separated string
-        RESULT_STRING=$(IFS=,; echo "${RESULT[*]}")
-
-        # Set outputs
-        echo "result=$RESULT_STRING" >> $GITHUB_ENV
-        echo "result=$RESULT_STRING" >> $GITHUB_OUTPUT
       env:
         NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
-
